version: 2
updates:
  - package-ecosystem: 'npm'
    directory: 'dev-client'
    target-branch: 'dependencies'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    open-pull-requests-limit: 20
    allow:
      - dependency-type: 'all'
    groups:
      babel:
        patterns:
          - '@babel/*'
      types:
        patterns:
          - '@types/*'
      expo:
        patterns:
          - '@expo/*'
          - 'expo*'
      react-native:
        patterns:
          - '@react-native/*'
          - 'react-native*'

  - package-ecosystem: 'bundler'
    directory: 'dev-client'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: 'all'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: 'all'
