name: Android Release

on:
  workflow_dispatch:
  schedule:
    - cron: '12 4 * * *'
  release:
    types: [published]

jobs:
  android-build-sign:
    name: Build and sign Android app
    uses: ./.github/workflows/build-shared-android.yml
    with:
      upload: 'true'
    secrets:
      MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
      GOOGLE_OAUTH_ANDROID_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_ANDROID_CLIENT_ID }}
      ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
      ANDROID_ALIAS: ${{ secrets.ANDROID_ALIAS }}
      ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      ANDROID_SERVICE_ACCOUNT_JSON_TEXT: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON_TEXT }}
