name: Dependabot auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.ref == 'refs/heads/depdendencies'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge ${{ github.event.pull_request.number }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
