on:
  workflow_call:
    inputs:
      upload:
        required: false
        type: string
        default: 'false'
    secrets:
      MAPBOX_DOWNLOADS_TOKEN:
        required: true
      GOOGLE_OAUTH_ANDROID_CLIENT_ID:
        required: false
      PUBLIC_MAPBOX_TOKEN:
        required: false
      ANDROID_SIGNING_KEY:
        required: false
      ANDROID_ALIAS:
        required: false
      ANDROID_KEY_STORE_PASSWORD:
        required: false
      ANDROID_KEY_PASSWORD:
        required: false
      ANDROID_SERVICE_ACCOUNT_JSON_TEXT:
        required: false

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Provide Mapbox secret key
        run: |
          mkdir -p $HOME/.gradle
          echo "MAPBOX_DOWNLOADS_TOKEN=${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}" >> $HOME/.gradle/gradle.properties

      - name: Set up config values
        if: ${{ inputs.upload == 'true' }}
        working-directory: ./dev-client/android
        run: |
          echo "GOOGLE_OAUTH_ANDROID_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_ANDROID_CLIENT_ID }}" >> .env
          echo "PUBLIC_MAPBOX_TOKEN=${{ secrets.PUBLIC_MAPBOX_TOKEN }}" >> .env

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: dev-client/package-lock.json

      - name: Install Node dependencies
        working-directory: dev-client
        run: npm ci

      - name: Set up our JDK environment
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-caches-

      - name: Bump Android version
        if: ${{ inputs.upload == 'true' }}
        working-directory: ./dev-client/android
        run: ./gradlew bumpPatchVersion

      # - name: Commit Android version bump
      #   if: ${{ inputs.upload == 'true' }}
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     file_pattern: 'dev-client/android/app/build.gradle'
      #     commit_message: 'build: bump Android version number'
      #     commit_user_name: 'GitHub Actions'
      #     commit_user_email: actions@users.noreply.github.com

      - name: Build Android app bundle
        working-directory: ./dev-client/android
        run: ./gradlew bundleRelease

      - name: Sign Android app bundle
        if: ${{ inputs.upload == 'true' }}
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ./dev-client/android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload App to Google Play
        if: ${{ inputs.upload == 'true' }}
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON_TEXT }}
          releaseName: Terraso LandPKS
          packageName: org.terraso.landpks
          releaseFiles: ./dev-client/android/app/build/outputs/bundle/release/*.aab
          track: internal
          status: draft
          inAppUpdatePriority: 2
