name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  build-android:
    runs-on: macos-latest
    needs: install-node-dependencies
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: |
            dev-client/package-lock.json
      - name: Install node dependencies
        working-directory: ./dev-client
        run: npm ci
      - name: Build android
        working-directory: ./dev-client/android
        run: ./gradlew build
