on:
  workflow_call:
    inputs:
      upload:
        required: false
        type: string
        default: 'false'
    secrets:
      MAPBOX_DOWNLOADS_TOKEN:
        required: true
      IOS_P12_BASE64:
        required: true
      IOS_MOBILE_PROVISION_BASE64:
        required: true
      IOS_TEAM_ID:
        required: true
      IOS_CERTIFICATE_PASSWORD:
        required: true
      APPLE_ISSUER_ID:
        required: false
      APPLE_KEY_ID:
        required: false
      APPLE_PRIVATE_KEY:
        required: false

jobs:
  ios-build:
    name: iOS Build
    runs-on: macos-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Enable build cache
        uses: mikehardy/buildcache-action@v2

      - name: Provide Mapbox secret key
        run: |
          echo "machine api.mapbox.com" >> $HOME/.netrc
          echo "login mapbox" >> $HOME/.netrc
          echo "password ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}" >> $HOME/.netrc
          chmod 600 $HOME/.netrc

      - name: Set up config values
        if: ${{ inputs.upload == 'true' }}
        working-directory: ./dev-client
        run: |
           echo "GOOGLE_OAUTH_IOS_CLIENT_ID =${{ secrets.GOOGLE_OAUTH_IOS_CLIENT_ID }}" >> .env
           echo "GOOGLE_OAUTH_IOS_URI_SCHEME =${{ secrets.GOOGLE_OAUTH_IOS_URI_SCHEME }}" >> .env
           echo "PUBLIC_MAPBOX_TOKEN =${{ secrets.PUBLIC_MAPBOX_TOKEN }}" >> .env

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: dev-client/package-lock.json

      - name: Install Node dependencies
        working-directory: dev-client
        run: npm ci

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: dev-client

      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: dev-client/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-

      - name: CocoaPod Install
        working-directory: dev-client/ios
        run: pod install

      - name: Build iOS App
        uses: yukiarrr/ios-build-action@v1.11.0
        with:
          project-path: dev-client/ios/Terraso LandPKS.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
          code-signing-identity: 'iPhone Distribution'
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          workspace-path: dev-client/ios/Terraso LandPKS.xcworkspace
          scheme: Terraso LandPKS
          increment-build-number: ${{ inputs.upload == 'true' && 'true' || '' }}

      - name: Commit iOS version bump
        if: github.ref != 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "dev-client/ios"
          commit_message: "build: bump iOS version number"
          commit_user_name: "GitHub Actions"
          commit_user_email: actions@users.noreply.github.com
          push_options: '--force'

      - name: Upload app to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        if: ${{ inputs.upload == 'true' }}
        with:
          app-path: 'output.ipa'
          issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_KEY_ID }}
          api-private-key: ${{ secrets.APPLE_PRIVATE_KEY }}
