name: Conventional Commits

on:
  merge_group:
  pull_request:
    branches:
      - main
      - dependencies
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-for-cc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Check for Conventional Commits
        uses: agenthunt/conventional-commit-checker-action@v2.0.0
