name: iOS Release

on:
  workflow_dispatch:
  schedule:
    - cron: '12 4 * * *'
  release:
    types: [published]

jobs:
  ios-build-sign:
    name: Build and sign iOS app
    uses: ./.github/workflows/build-shared-ios.yml
    with:
      upload: 'true'
    secrets:
      MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
      GOOGLE_OAUTH_IOS_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_IOS_CLIENT_ID }}
      GOOGLE_OAUTH_IOS_URI_SCHEME: ${{ secrets.GOOGLE_OAUTH_IOS_URI_SCHEME }}
      PUBLIC_MAPBOX_TOKEN: ${{ secrets.PUBLIC_MAPBOX_TOKEN }}
      IOS_P12_BASE64: ${{ secrets.IOS_P12_BASE64 }}
      IOS_MOBILE_PROVISION_BASE64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
      IOS_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}
      IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
      APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
      APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
      APPLE_PRIVATE_KEY: ${{ secrets.APPLE_PRIVATE_KEY }}
