name: iOS Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (i.e. 1.0.1)'
        default: '1.0.0'
        type: string
        required: true
      APP_BUILD:
        description: 'Build number (i.e. 153)'
        default: '153'
        type: string
        required: true
      environment:
        description: 'Release environment'
        type: environment
        required: true
  push:
    tags:
      - 'v[0-9]+'

jobs:
  ios-build-sign:
    name: Build and sign iOS app
    uses: ./.github/workflows/build-shared-ios.yml
    with:
      upload: 'true'
      APP_BUILD: ${{ github.ref_name }}
    secrets:
      MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
      PUBLIC_MAPBOX_TOKEN: ${{ secrets.PUBLIC_MAPBOX_TOKEN }}
      APPLE_P12_BASE64: ${{ secrets.APPLE_P12_BASE64 }}
      APPLE_MOBILE_PROVISION_BASE64: ${{ secrets.APPLE_MOBILE_PROVISION_BASE64 }}
      APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
      APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
      APPLE_APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APPLE_APP_STORE_CONNECT_PRIVATE_KEY }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
