name: iOS Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  ios-build-and-sign:
    name: iOS Build and Sign
    runs-on: macOS-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Enable build cache
        uses: mikehardy/buildcache-action@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: dev-client/package-lock.json

      - name: Install Node dependencies
        working-directory: dev-client
        run: npm ci

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: dev-client

      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: |
            dev-client/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Provide Mapbox secret key
        env:
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
        run: |
          echo "machine api.mapbox.com" >> $HOME/.netrc
          echo "login mapbox" >> $HOME/.netrc
          echo "password $MAPBOX_DOWNLOADS_TOKEN" >> $HOME/.netrc
          chmod 600 $HOME/.netrc

      - name: Set up config values
        working-directory: ./dev-client
        env:
          GOOGLE_OAUTH_APP_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_APP_IOS_CLIENT_ID }}
          GOOGLE_OAUTH_IOS_URI_SCHEME: ${{ secrets.GOOGLE_OAUTH_IOS_URI_SCHEME }}
          PUBLIC_MAPBOX_TOKEN: ${{ secrets.PUBLIC_MAPBOX_TOKEN }}
        run: |
          mv .env.sample .env
          for env_var in $(echo GOOGLE_OAUTH_APP_CLIENT_ID secrets.GOOGLE_OAUTH_IOS_URI_SCHEME PUBLIC_MAPBOX_TOKEN);
          do
            sed -i -E "s/^($env_var=).*/${!env_var}/" .env
          done

      - name: CocoaPod Install
        working-directory: dev-client/ios
        run: pod install

      - name: Bump Version
        uses: yanamura/ios-bump-version@v1
        with:
          version: '1.0'
          project-path: dev-client/ios

      - name: Commit version bump
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add dev-client/ios
          git commit -m "build: bump version number"
          git push

      - name: Build iOS App
        uses: yukiarrr/ios-build-action@v1.11.0
        with:
          project-path: dev-client/ios/Terraso LandPKS.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
          code-signing-identity: 'iPhone Distribution'
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          workspace-path: dev-client/ios/Terraso LandPKS.xcworkspace
          scheme: Terraso LandPKS

      - name: Upload app to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: 'output.ipa'
          issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_KEY_ID }}
          api-private-key: ${{ secrets.APPLE_PRIVATE_KEY }}
