name: iOS Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  ios-build-setup:
    name: iOS build setup
    runs-on: macos-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Set up config values
        working-directory: ./dev-client
        run: |
           echo "GOOGLE_OAUTH_IOS_CLIENT_ID =${{ secrets.GOOGLE_OAUTH_IOS_CLIENT_ID }}" >> .env
           echo "GOOGLE_OAUTH_IOS_URI_SCHEME =${{ secrets.GOOGLE_OAUTH_IOS_URI_SCHEME }}" >> .env
           echo "PUBLIC_MAPBOX_TOKEN =${{ secrets.PUBLIC_MAPBOX_TOKEN }}" >> .env

      - name: Bump iOS build version
        uses: yanamura/ios-bump-version@v1
        with:
          version: '1.0'
          project-path: dev-client/ios

      - name: Commit iOS version bump
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event_name == 'pull_request'
        with:
          file_pattern: "dev-client/ios"
          commit_message: "build: bump iOS version number"
          commit_user_name: "GitHub Actions"
          commit_user_email: actions@users.noreply.github.com

  ios-build-sign:
    name: Build and sign iOS app
    needs: ios-build-setup
    uses: ./.github/workflows/build-shared-ios.yml
    secrets:
      MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
      IOS_P12_BASE64: ${{ secrets.IOS_P12_BASE64 }}
      IOS_MOBILE_PROVISION_BASE64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
      IOS_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}
      IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}

  ios-upload:
    name: iOS upload build
    runs-on: macos-latest
    steps:
      - name: Upload app to TestFlight
        runs-on: macos-latest
        needs: ios-build-sign
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: 'output.ipa'
          issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_KEY_ID }}
          api-private-key: ${{ secrets.APPLE_PRIVATE_KEY }}
