name: iOS Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  ios-build-and-sign:
    name: iOS Build and Sign
    runs-on: macOS-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Enable build cache
        uses: mikehardy/buildcache-action@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: dev-client/package-lock.json

      - name: Install Node dependencies
        working-directory: dev-client
        run: npm ci

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: dev-client

      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: |
            dev-client/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Provide Mapbox secret key
        run: |
          echo "machine api.mapbox.com" >> $HOME/.netrc
          echo "login mapbox" >> $HOME/.netrc
          echo "password ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}" >> $HOME/.netrc
          chmod 600 $HOME/.netrc

      - name: Set up config values
        working-directory: ./dev-client
        run: |
           echo "GOOGLE_OAUTH_IOS_CLIENT_ID =${{ secrets.GOOGLE_OAUTH_IOS_CLIENT_ID }}" >> .env
           echo "GOOGLE_OAUTH_IOS_URI_SCHEME =${{ secrets.GOOGLE_OAUTH_IOS_URI_SCHEME }}" >> .env
           echo "PUBLIC_MAPBOX_TOKEN =${{ secrets.PUBLIC_MAPBOX_TOKEN }}" >> .env

      - name: CocoaPod Install
        working-directory: dev-client/ios
        run: pod install

      - name: Bump Version
        uses: yanamura/ios-bump-version@v1
        with:
          version: '1.0'
          project-path: dev-client/ios

      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "dev-client/ios"
          commit_message "build: bump iOS version number"
          commit_user_name: "GitHub Actions"
          commit_user_email: actions@users.noreply.github.com

      - name: Build iOS App
        uses: yukiarrr/ios-build-action@v1.11.0
        with:
          project-path: dev-client/ios/Terraso LandPKS.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
          code-signing-identity: 'iPhone Distribution'
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          workspace-path: dev-client/ios/Terraso LandPKS.xcworkspace
          scheme: Terraso LandPKS

      - name: Upload app to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: 'output.ipa'
          issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_KEY_ID }}
          api-private-key: ${{ secrets.APPLE_PRIVATE_KEY }}
