name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: |
            dev-client/package-lock.json

      - name: Install node dependencies
        working-directory: ./dev-client
        run: npm ci

      - name: Run lint checks
        working-directory: ./dev-client
        run: npm run lint

      - name: Type check
        working-directory: ./dev-client
        run: npm run check-ts
